import from mozilla upstream: - Bug 933023 - UITour: Add preference to disable HTTPS check for testing/development. r=MattN (1758dd30907) - Merge m-c to fxteam (f54e32562c9) - Bug 933984 - Fix "this._mutationObserver is undefined" error on new tab page. r=gavin (0429ffc7c9a) - Bug 933646 - Blackboxing a program in the shader editor should hide the rendered geometry, r=rcampbell (12fcbdad3bc) - Bug 930928 - Shader compilation errors should be displayed in the editor, r=rcampbell,anton (72b34a49ec8) - Bug 934487 - Fix "TypeError: this.markup is undefined" in devtools b-c runs; r=pbrosset (2f75f5bc766) - Bug 867776 - Move URLCryptoKeyManager serialization to off the main-thread. r=Yoric (5c914cc9b8f) - Bug 853356 - Part1 Add new permissions and prompt for mutiple permissions request. r=fabrice, felipc, wjohnston, mrbkap, jimm (af01190bbc1) - Bug 853356 - Part2 Add MediaPermissionGonk.h and MediaPermissionGonk.cpp to implement ContentPermissionPrompt. r=jesup (095eff90e89) - Bug 853356 - Part3 Pass a string array instead of a single string to support multiple permissions request. r=khuey (620bb632ca8) - Bug 853356 - Test: Check mediastream track according to request type. r=jsmith (c1c648a84ca) - Bumping gaia.json for 2 gaia-central revision(s) a=gaia-bump (15a9fb36bf2) - Bumping gaia.json for 1 gaia-central revision(s) a=gaia-bump (1213e878152) - Bug 932201 - [B2G][DSDS] Gecko needs to properly download MMS for non-active SIM. r=ctai,vicamo (cbca30cd636) - Bug 908535 - Part1: STK-OPEN CHANNEL proactive command IDL change. r=yoshi, hsinyi. (26bdd3dd0e7) - Bug 908535 - Part2: Process STK OPEN CHANNEL cmd and ctlvs in ril. r=yoshi (b80198b2b1a) - Bug 908535 - Part3: xpcshell test for OPEN CHANNEL proactive cmd. r=yoshi (28fc8c36dc0) - Bug 908536 - Part1: STK BIP-CLOSE_CHANNEL, RECEIVE\SEND_DATA commands IDL. r=yoshi, hsinyi. (66569724636) - Bug 908536 - Part2: STK BIP CLOSE_CHANNEL, RECEIVE/SEND_DATA handle in RIL. r=yoshi. (8ac88959d14) - Bug 908536 - Part3: STK BIP-CLOSE_CHANNEL, RECEIVE/SEND_DATA xpcshell test. r=yoshi. (2b9e511bd44) - Bug 904298 - Implement mozilla::{AssertAppPrincipal,CheckPermission}. r=sicking (b6c02856c2b) - Bumping gaia.json for 2 gaia-central revision(s) a=gaia-bump (5c8e890e66e) - Bumping gaia.json for 2 gaia-central revision(s) a=gaia-bump (c7bb7fe2966) - Bumping gaia.json for 2 gaia-central revision(s) a=gaia-bump (9f7c6fbfc41) - Bug 927711 - B2G MMS : Handle message delivered timestamp for delivery report (part 1, DOM API IDL). r=hsinyi (60b46de155e) - Bug 927711 - B2G MMS : Handle message delivered timestamp for delivery report (part 2, implementation). r=ctai (cdca0459164) - Bug 932682 - [bluedroid] Support Pair/Unpair, Bond state changed callback, r=echou (7fd0d33f4d5) - Backed out changeset 6cb70cc44e8c (bug 927711) for build failure/bustage (8093b210caf) - Backed out changeset f27a2aba0db2 (bug 927711) for build failure/bustage (79a4977c178) - Bumping gaia.json for 2 gaia-central revision(s) a=gaia-bump (629891f186a) - Bumping gaia.json for 2 gaia-central revision(s) a=gaia-bump (03c6682b14b) - Bumping gaia.json for 4 gaia-central revision(s) a=gaia-bump (9077bffdedc) - Bug 920595 - Mochitest for verifying state transitions in Media Recording API. r=roc (4ad5944819c) - Bug 934274 - [app manager] changed invalidLaunchPath to accessFailedLaunchPath and edited the text. r=jryans (d6606a229d6) - Bug 934207 - Add browser_thumbnails_background_crash.js to browser.ini r=jhammel,markh (8af62f2f109) - Bumping gaia.json for 1 gaia-central revision(s) a=gaia-bump (3da424dcdb4) - Bug 910768 - Add a link to the marketplace in the "No apps installed for this url" toast; r=wesj (5a8096e8a6b) - Bug 904298 - Implement mozilla::{AssertAppPrincipal,CheckPermission}. r=sicking (ae48603c295) - Bug 904298 - Bustage fix. (b6f721c3818) - Backed out 2 changesets (bug 904298) DONTBUILD (2139f81568f) - Bumping gaia.json for 2 gaia-central revision(s) a=gaia-bump (755d6b8f812) - Bug 931746 - Only handle events from our direct descendants. r=yxl (77774a22418) - Merge m-c to b2g-inbound (6e1016249ff) - Bug 853356 - Part1 Add new permissions and prompt for mutiple permissions request. r=fabrice, felipc, wjohnston, mrbkap, jimm (0d61f474cee) - Bug 853356 - Part2 Add MediaPermissionGonk.h and MediaPermissionGonk.cpp to implement ContentPermissionPrompt. r=jesup (02b2d7381ab) - Bug 853356 - Part3 Pass a string array instead of a single string to support multiple permissions request. r=khuey (554000b50c2) - Bug 853356 - Test: Check mediastream track according to request type. r=jsmith (bf2f8eb2e05) - Bumping gaia.json for 2 gaia-central revision(s) a=gaia-bump (774fb182a47) - Backout 3c0d710561bf (bug 927363) due to causing bug 930296. (9768ef5bda7) - Backout dc03ef5cd3fd (69842704991) - Backout 6d33ac3a2b14 (3a9ca16110f) - Backout 2baeee8eb114 (a582f5f1311) - Backout 3903cb4b779f (3b2be7096b1) - Backout 87b5e35236ef (bug 931746) breaks UI tests (c114de060ce) - merge mozilla-central to fx-team (cffda8a9dab) - Backout 90d6f7ce0fc2 (bug 920935) not needed anymore (r=backout) (9b93a5dd2f9) - Bug 930548: collect more per-addon Telemetry details; r=unfocused (b9ffd5b8aae) - Bug 916797 - --run-until-failure mochitest option should support running multiple tests. r=jmaher (e69f72c0e7e) - Bug 886014 - Don't assume that all vnd.youtube URLs have params. r=mfinkle (4635c962f68) - Bug 932937 - Images are resized on the server-side for image preview tooltips. r=harth (582fd8a44f4) - Bug 934131 - Remove k12.sd.us from PSL. r=gerv (58284e8108a) - Bug 754344 - Make in-content prefs navigation look like about:addons r=jaws (43df2515e7f) - merge fx-team to mozilla-central (c0c81ee736f) - merge b2g-inbound to mozilla-central (3f9b93be916) - Bumping gaia.json for 2 gaia-central revision(s) a=gaia-bump (93ad0790319) - Bumping gaia.json for 2 gaia-central revision(s) a=gaia-bump (9d2aa1925ca) - Bumping gaia.json for 2 gaia-central revision(s) a=gaia-bump (f9b732f5ffc) - Bumping gaia.json for 2 gaia-central revision(s) a=gaia-bump (195c29e3216) - merge mozilla-central to b2g-inbound (1d334f5365b) - Bumping gaia.json for 2 gaia-central revision(s) a=gaia-bump (e174e79a577) - Bumping gaia.json for 2 gaia-central revision(s) a=gaia-bump (dcb5ff3d8d8) - Bumping gaia.json for 1 gaia-central revision(s) a=gaia-bump (6d724798324) - Bumping gaia.json for 2 gaia-central revision(s) a=gaia-bump (23a07787775) - Bumping gaia.json for 2 gaia-central revision(s) a=gaia-bump (5f3805a50e3) - Merge fx-team to m-c. (4fdf1ddb095)